project_name: pbauthor

# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-X 'github.com/pathbird/pbauthor/internal/version.Version={{ .Version }}'"
archives:
  - replacements:
      darwin: macos
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

scoop:
  bucket:
    owner: pathbird
    name: scoop-bucket

  commit_author: &commit_author
    email: goreleaserbot@pathbird.com

  homepage: "https://pathbird.com/"

brews:
  - tap:
      owner: pathbird
      name: homebrew-tap
    commit_author: *commit_author
